"""assignment ownership fields

Revision ID: 76cd23c58399
Revises: 1cbd5cd09099
Create Date: 2026-01-02 14:28:53.071790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76cd23c58399'
down_revision: Union[str, Sequence[str], None] = '1cbd5cd09099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.add_column('assignments', sa.Column('assigned_to_user_id', sa.Integer(), nullable=True))
    op.add_column('assignments', sa.Column('assigned_at', sa.DateTime(), nullable=True))
    op.add_column('assignments', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('assignments', sa.Column('report_submitted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_assignments_assigned_to_user_id'), 'assignments', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_assignments_created_by_user_id'), 'assignments', ['created_by_user_id'], unique=False)
    op.create_foreign_key(None, 'assignments', 'users', ['assigned_to_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'assignments', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_index(op.f('ix_assignments_created_by_user_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_assigned_to_user_id'), table_name='assignments')
    op.drop_column('assignments', 'report_submitted_at')
    op.drop_column('assignments', 'completed_at')
    op.drop_column('assignments', 'assigned_at')
    op.drop_column('assignments', 'assigned_to_user_id')
    op.drop_column('assignments', 'created_by_user_id')
    # ### end Alembic commands ###
